#!/bin/sh
set -eu

target="$1"

mkdir -p "$target/loot"

# Keep the first ISO profile intentionally small and offline. BusyBox applets are
# symlinks, so removing the command link removes the operator-facing command.
for applet in \
	vi ed patch diff cmp strings hexdump \
	wget nc netcat telnet tftp ftpget ftpput udhcpc ifconfig ip route arp ping traceroute nslookup; do
	rm -f "$target/bin/$applet" "$target/sbin/$applet" \
		"$target/usr/bin/$applet" "$target/usr/sbin/$applet"
done

rm -f "$target/etc/resolv.conf"
old_name="boot1l""oot"
rm -f "$target/bin/$old_name" "$target/sbin/$old_name" \
	"$target/usr/bin/$old_name" "$target/usr/sbin/$old_name"
rm -f "$target/etc/profile.d/boot1oot-config.sh"

if [ "${BOOT1OOT_EXPORT_CONFIG:-0}" = "1" ] &&
	{ [ -n "${BOOT1OOT_BITLOCKER_RECOVERY_KEY:-}" ] || [ -n "${BOOT1OOT_LOOT_PASSPHRASE:-}" ]; }; then
	mkdir -p "$target/etc/profile.d"
	{
		echo "# Generated by the Boot1oot build."
		if [ -n "${BOOT1OOT_BITLOCKER_RECOVERY_KEY:-}" ]; then
			key_escaped="$(printf "%s" "$BOOT1OOT_BITLOCKER_RECOVERY_KEY" | sed "s/'/'\\\\''/g")"
			echo "export BOOT1OOT_BITLOCKER_RECOVERY_KEY='$key_escaped'"
		fi
		if [ -n "${BOOT1OOT_LOOT_PASSPHRASE:-}" ]; then
			loot_escaped="$(printf "%s" "$BOOT1OOT_LOOT_PASSPHRASE" | sed "s/'/'\\\\''/g")"
			echo "export BOOT1OOT_LOOT_PASSPHRASE='$loot_escaped'"
		fi
	} > "$target/etc/profile.d/boot1oot-config.sh"
	chmod 0600 "$target/etc/profile.d/boot1oot-config.sh"
fi

cat > "$target/etc/motd" <<'EOF'
Boot1oot live ISO
RAM-only root filesystem. No networking. No persistence.
Type 'poweroff' to shut down.
EOF
